# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.07.1
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Initialise the OCaml environment
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Environment
        run: |
            eval $(opam env)
            opam --version
            ocaml --version

      - name: Install ocamlbuild
        run: opam install --yes ocamlbuild.0.14.0
        
      - name: Install sphinx
        run: pip install Sphinx==2.4.4
        
      - name: Install bikeshed
        run: |
            git clone https://github.com/tabatkins/bikeshed.git
            pip install --editable $PWD/bikeshed
            bikeshed update
            
      - name: Wasm testsuite
        run: ./interpreter/meta/travis/build-test.sh
        
      #- name: Deploy documentation
      #  run: ./document/travis-deploy.sh
